server {
    listen 80;

    server_name nimrod.raui.uk;

    client_max_body_size 100M;

    # FRONTEND
    location / {
        proxy_pass http://frontend:80;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # BACKEND API
    location /api/ {
        proxy_pass http://backend:3001/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # BACKEND WS
    location /ws {
        proxy_pass http://backend:3001/ws;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
    }

    # FOUNDRY
    location /foundry/ {
        proxy_pass http://127.0.0.1:30001/foundry/;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 86400;
    }
}